# Scene configuraton
samples_per_pixel = 1000
samples_step_size = 10
max_bounces = 50
image_width = 1000
bg = 0.0

# Camera
fov = 20.0
aspect_ratio = 1.0
from = [1.2, 0.2, -2.85]
at = [0.05, 0.05, -0.08]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005


# Materials for meshes and objects
[materials.light]
kind = "light"
color = 6.5

[materials.red]
kind = "solid"
color = [0.9, 0.2, 0.1]

[materials.dragon]
kind = "specular"
color = [0.1, 0.2, 0.07]
spec_color = 0.3
smoothness = 0.7
spec_prob = 0.2

[materials.gold]
kind = "metal"
color = [0.8, 0.6, 0.2]
fuzz = 0.01

[materials.silver]
kind = "specular"
color = [0.2, 0.3, 0.8]
spec_color = 0.8
smoothness = 0.4
spec_prob = 0.8


# .obj meshes (only vertices are used)
[[meshes]]
path = "assets/Dragon_8K.obj"
material = "dragon"
rotate = 28.0


# Additional scene objects

# "sun"
[[objects]]
kind = "sphere"
center = [1.4, 0.9, -0.8]
r = 0.7
material = "light"

# ground
[[objects]]
kind = "sphere"
center = [0.0, -100.0, -1.0]
r = 99.7
material = "gold"

# metalic shell
[[objects]]
kind = "sphere"
center = [0.0, -100.0, -1.0]
r = 100.9
material = "silver"

[[objects]]
kind = "sphere"
center = [0.3, -0.1, 0.0]
r = 0.1
material = "gold"

[[objects]]
kind = "sphere"
center = [0.41, -0.2, -0.5]
r = 0.08
material = "gold"

[[objects]]
kind = "sphere"
center = [0.42, -0.23, 0.1]
r = 0.07
material = "gold"
