# Scene configuraton
samples_per_pixel = 1000
samples_step_size = 100
max_bounces = 80
image_width = 1000
bg = 0.0

# Camera
fov = 40.0
aspect_ratio = 1.0
from = [1.0, 2.0, -6.0]
at = [0.0, 1.0, 0.0]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005

# Materials for meshes and objects
[materials.dragon]
kind = "specular"
color = [0.1, 0.2, 0.07]
spec_color = 0.3
smoothness = 0.7
spec_prob = 0.7

[materials.gold]
kind = "specular"
color = [0.8, 0.6, 0.2]
spec_color = 1.0
smoothness = 0.9
spec_prob = 0.8

[materials.light]
kind = "light"
color = 6.0

[materials.perlin]
kind = "noise"
scale = 4.0

# .obj meshes (only vertices are used)
[[meshes]]
path = "assets/Dragon_8K.obj"
material = "dragon"
scale = 3.0
rotate = 55.0
translate = [0.0, 1.0, 0.0]


# Additional scene objects

# "sun"
[[objects]]
kind = "sphere"
center = [-2.4, 2.9, -5.0]
r = 2.5
material = "light"

[[objects]]
kind = "sphere"
center = [1.5, 0.7, -1.0]
r = 0.7
material = "gold"

[[objects]]
kind = "sphere"
center = [0.0, -1000.0, 0.0]
r = 1000.0
material = "perlin"
