# Scene configuration
samples_per_pixel = 1200
samples_step_size = 10
max_bounces = 15
image_width = 1200
bg = 0.01

# Camera
fov = 40.0
aspect_ratio = 1.0
from = [0.5, 0.5, -1.35]
at = [0.5, 0.5, 0.0]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005


# Materials for meshes and objects
[materials.light]
kind = "light"
color = [22.0, 21.0, 19.0]

[materials.red]
kind = "solid"
color = [0.65, 0.05, 0.05]

[materials.green]
kind = "solid"
color = [0.12, 0.45, 0.15]

[materials.blue]
kind = "solid"
color = [0.12, 0.25, 0.55]

[materials.white]
kind = "solid"
color = 0.73

[materials.mirror]
kind = "metal"
color = 0.93
fuzz = 0.0

[materials.marble]
kind = "specular"
color = [0.7, 0.55, 0.4]
smoothness = 0.5
spec_prob = 0.1

# Additional scene objects

[[objects]]
kind = "noise_sphere"
center = [0.5, 0.4, 0.5]
r = 0.42
subdivisions = 7
subtract = false
frac_inv = 2.0
noise_depth = 9
seed = "big ears"
material = "marble"

[[objects]]
kind = "box"
vert1 = [0.0, 0.0, 0.0]
vert2 = [1.0, 1.0, 1.0]
material = "white"
density = 0.01

[[objects]]
kind = "sphere"
center = [0.4, 0.4, 1.0]
r = 0.15
material = "light"


# Cornell Box

# [[objects]]
# kind = "quad"
# q = [0.61, 0.999, 0.59]
# u = [-0.23, 0.0, 0.0]
# v = [0.0, 0.0, -0.18]
# material = "light"

[[objects]]
kind = "quad"
q = [1.0, 0.0, 0.0]
u = [0.0, 1.0, 0.0]
v = [0.0, 0.0, 1.0]
material = "green"

[[objects]]
kind = "quad"
q = [0.0, 0.0, 0.0]
u = [0.0, 1.0, 0.0]
v = [0.0, 0.0, 1.0]
material = "red"

[[objects]]
kind = "quad"
q = [0.0, 0.0, 0.0]
u = [1.0, 0.0, 0.0]
v = [0.0, 0.0, 1.0]
# material = "white"
material = "mirror"

[[objects]]
kind = "quad"
q = [0.0, 0.0, 1.0]
u = [1.0, 0.0, 0.0]
v = [0.0, 1.0, 0.0]
# material = "blue"
material = "white"

[[objects]]
kind = "quad"
q = [1.0, 1.0, 1.0]
u = [-1.0, 0.0, 0.0]
v = [0.0, 0.0, -1.0]
# material = "white"
# material = "mirror"
material = "blue"
