# Scene configuration
samples_per_pixel = 500
samples_step_size = 10
max_bounces = 5
image_width = 1200
bg = 0.0

# Camera
fov = 6.0
aspect_ratio = 1.0
from = [0.0, 1.0, 11.0]
at = [0.0, 0.0, 0.0]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005


# Materials for meshes and objects
[materials.ground]
kind = "noise"
color = [0.2, 0.6, 0.8]
scale = 20.0

[materials.jade]
kind = "metal"
color = [0.2, 0.6, 0.8]
fuzz = 0.1

[materials.marble]
kind = "specular"
color = [0.7, 0.55, 0.4]
smoothness = 0.1
spec_prob = 0.06

[materials.gold]
kind = "metal"
color = [0.8, 0.6, 0.2]
fuzz = 0.4

[materials.light]
kind = "light"
color = [15.0, 13.0, 11.0]

[materials.dim_light]
kind = "light"
color = [0.3, 0.2, 0.1]

[materials.crystal]
kind = "dielectric"
ref_index = 3.0

[materials.glass]
kind = "dielectric"
ref_index = 1.2

# Additional scene objects

# ground
[[objects]]
kind = "sphere"
center = [0.0, -100.5, -1.0]
r = 100.0
material = "ground"

[[objects]]
kind = "sphere"
center = [0.0, -100.5, -1.0]
r = 100.1
material = "crystal"

# sky
[[objects]]
kind = "sphere"
center = [0.0, -100.5, -1.0]
r = 130.0
material = "jade"

# lights

[[objects]]
kind = "sphere"
center = [0.0, -100.5, -11.0]
r = 90.5
material = "dim_light"

[[objects]]
kind = "sphere"
center = [-3.5, 1.2, 2.2]
r = 1.2
material = "light"



[[objects]]
kind = "sphere"
center = [0.0, 0.0, 0.0]
r = 0.3
material = "ground"

[[objects]]
kind = "sphere"
center = [0.0, 0.0, 0.0]
r = 0.4
material = "glass"

# iceberg
[[objects]]
kind = "noise_sphere"
center = [0.0, 0.0, 0.0]
r = 0.4
subdivisions = 7
subtract = true
frac_inv = 2.0
noise_depth = 9
seed = "raymart"
material = "marble"
