# Scene configuraton
samples_per_pixel = 1000
samples_step_size = 0
max_bounces = 50
image_width = 800
bg = 0.0

# Camera
fov = 20.0
aspect_ratio = 1.6
from = [26.0, 3.0, 6.0]
at = [0.0, 2.0, 0.0]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005


# Materials for meshes and objects
[materials.perlin]
kind = "noise"
scale = 4.0

[materials.light1]
kind = "light"
color = [0.0, 2.0, 2.0]

[materials.light2]
kind = "light"
color = [4.0, 0.0, 4.0]

# Additional scene objects

[[objects]]
kind = "sphere"
center = [0.0, -1000.0, 0.0]
r = 1000.0
material = "perlin"

[[objects]]
kind = "sphere"
center = [0.0, 2.0, 0.0]
r = 2.0
material = "perlin"

[[objects]]
kind = "sphere"
center = [0.0, 8.0, 0.0]
r = 2.0
material = "light1"

[[objects]]
kind = "quad"
q = [3.0, 1.0, -2.0]
u = [2.0, 0.0, 0.0]
v = [0.0, 2.0, 0.0]
material = "light2"
