[package]
name = "raymart"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1

[[bench]]
name = "bench_main"
harness = false

[dependencies]
anyhow = "1.0.104"
glam = "0.33.8"
image = "0.25.10"
rand = "0.10.3"
rand_xoshiro = "0.8.1"
rayon = "1.12.0"
sdl2 = { version = "0.38.0", features = ["image"] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
tobj = { version = "4.0.5", default-features = false, features = [] }
toml = "1.1.6"
wide = "1.7.1"
gif = "0.14.2"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
simple_test_case = "1"
