# Scene configuraton
samples_per_pixel = 50
max_bounces = 50
image_width = 800
bg = 0.0

# Camera
fov = 40.0
aspect_ratio = 1.0
from = [1.2, 0.2, -0.85]
at = [0.05, 0.05, -0.08]
v_up = [0.0, 1.0, 0.0]

# Debug point view
as_points = false
point_radius = 0.005


# Materials for meshes and objects
[materials.light]
kind = "light"
color = 16.5

[materials.red]
kind = "solid"
color = [0.9, 0.2, 0.1]

[materials.gold]
kind = "metal"
color = [0.8, 0.6, 0.2]
fuzz = 0.01

[materials.silver]
kind = "metal"
color = [0.2, 0.3, 0.8]
fuzz = 1.0


# .obj meshes (only vertices are used)
[[meshes]]
path = "assets/Dragon_8K.obj"
material = "red"
rotate = 15.0


# Additional scene objects

# "sun"
[[objects]]
kind = "sphere"
center = [1.4, 0.9, -0.8]
r = 0.7
material = "light"

# ground
[[objects]]
kind = "sphere"
center = [0.0, -100.0, -1.0]
r = 99.7
material = "gold"

# metalic shell
[[objects]]
kind = "sphere"
center = [0.0, -100.0, -1.0]
r = 100.9
material = "silver"
